// RUN: cir-opt %s -cir-call-conv-lowering -o - | FileCheck %s

// Verify that the CallConvLowering pass correctly handles ABI lowering
// using the LLVM ABI Lowering Library's X86_64 classifier.
// Record coercion is enabled (the default for cir-opt) since the test
// uses plain C structs that are trivially copyable.

!s32i = !cir.int<s, 32>
!s64i = !cir.int<s, 64>
!u128i = !cir.int<u, 128>
!u64i = !cir.int<u, 64>
!rec_div_t = !cir.record<struct "div_t" {!s32i, !s32i}>
!rec_single = !cir.record<struct "single" {!s32i}>
!rec_two_i64 = !cir.record<struct "two_i64" {!s64i, !s64i}>
!rec_three_i64 = !cir.record<struct "three_i64" {!s64i, !s64i, !s64i}>

module {
  // --- Scalars: unchanged ---

  cir.func @add(%a : !s32i, %b : !s32i) -> !s32i {
    %r = cir.binop(add, %a, %b) : !s32i
    cir.return %r : !s32i
  }
  // CHECK: cir.func @add(%arg0: !s32i, %arg1: !s32i) -> !s32i

  cir.func @ret_i64() -> !s64i {
    %v = cir.const #cir.int<42> : !s64i
    cir.return %v : !s64i
  }
  // CHECK: cir.func @ret_i64() -> !s64i

  cir.func @void_func() {
    cir.return
  }
  // CHECK: cir.func @void_func()

  cir.func @scalar_args(%a : !s32i, %b : !s64i) -> !s32i {
    cir.return %a : !s32i
  }
  // CHECK: cir.func @scalar_args(%arg0: !s32i, %arg1: !s64i) -> !s32i

  // --- Struct return coercion (memory-based) ---

  // div_t {i32, i32} (8 bytes) -> coerced to u64 via memory
  cir.func @mock_div(%n : !s32i, %d : !s32i) -> !rec_div_t {
    %result = cir.alloca !rec_div_t, !cir.ptr<!rec_div_t>, ["result"] {alignment = 4 : i64}
    %val = cir.load %result : !cir.ptr<!rec_div_t>, !rec_div_t
    cir.return %val : !rec_div_t
  }
  // CHECK: cir.func @mock_div(%arg0: !s32i, %arg1: !s32i) -> !u64i
  // CHECK:   %[[VAL:.*]] = cir.load
  // CHECK:   %[[A:.*]] = cir.alloca !rec_div_t, !cir.ptr<!rec_div_t>, ["coerce"]
  // CHECK:   cir.store %[[VAL]], %[[A]]
  // CHECK:   %[[P:.*]] = cir.cast bitcast %[[A]] : !cir.ptr<!rec_div_t> -> !cir.ptr<!u64i>
  // CHECK:   %[[R:.*]] = cir.load %[[P]] : !cir.ptr<!u64i>, !u64i
  // CHECK:   cir.return %[[R]] : !u64i

  // Single-field struct {i32} (4 bytes) -> coerced to s32i
  cir.func @ret_single() -> !rec_single {
    %tmp = cir.alloca !rec_single, !cir.ptr<!rec_single>, ["tmp"] {alignment = 4 : i64}
    %val = cir.load %tmp : !cir.ptr<!rec_single>, !rec_single
    cir.return %val : !rec_single
  }
  // CHECK: cir.func @ret_single() -> !s32i
  // CHECK:   %[[V:.*]] = cir.load {{.*}} : !cir.ptr<!rec_single>, !rec_single
  // CHECK:   %[[A:.*]] = cir.alloca !rec_single, !cir.ptr<!rec_single>, ["coerce"]
  // CHECK:   cir.store %[[V]], %[[A]]
  // CHECK:   %[[P:.*]] = cir.cast bitcast %[[A]] : !cir.ptr<!rec_single> -> !cir.ptr<!s32i>
  // CHECK:   %[[R:.*]] = cir.load %[[P]] : !cir.ptr<!s32i>, !s32i
  // CHECK:   cir.return %[[R]] : !s32i

  // Two i64 struct {i64, i64} (16 bytes) -> coerced to {s64i, s64i}
  cir.func @ret_two_i64() -> !rec_two_i64 {
    %tmp = cir.alloca !rec_two_i64, !cir.ptr<!rec_two_i64>, ["tmp"] {alignment = 8 : i64}
    %val = cir.load %tmp : !cir.ptr<!rec_two_i64>, !rec_two_i64
    cir.return %val : !rec_two_i64
  }
  // CHECK: cir.func @ret_two_i64() -> !rec_anon_struct
  // CHECK:   %[[V:.*]] = cir.load {{.*}} : !cir.ptr<!rec_two_i64>, !rec_two_i64
  // CHECK:   %[[A:.*]] = cir.alloca !rec_two_i64, !cir.ptr<!rec_two_i64>, ["coerce"]
  // CHECK:   cir.store %[[V]], %[[A]]
  // CHECK:   %[[P:.*]] = cir.cast bitcast %[[A]] : !cir.ptr<!rec_two_i64> -> !cir.ptr<!rec_anon_struct>
  // CHECK:   %[[R:.*]] = cir.load %[[P]] : !cir.ptr<!rec_anon_struct>, !rec_anon_struct
  // CHECK:   cir.return %[[R]] : !rec_anon_struct

  // Three i64 struct {i64, i64, i64} (24 bytes) -> sret
  cir.func @ret_three_i64() -> !rec_three_i64 {
    %tmp = cir.alloca !rec_three_i64, !cir.ptr<!rec_three_i64>, ["tmp"] {alignment = 8 : i64}
    %val = cir.load %tmp : !cir.ptr<!rec_three_i64>, !rec_three_i64
    cir.return %val : !rec_three_i64
  }
  // CHECK: cir.func @ret_three_i64(%arg0: !cir.ptr<!rec_three_i64> {llvm.align = 8 : i64, llvm.dead_on_unwind, llvm.noalias, llvm.sret = !rec_three_i64, llvm.writable})
  // CHECK:   cir.store %{{.*}}, %arg0 : !rec_three_i64
  // CHECK:   cir.return

  // --- Call-site rewriting ---

  cir.func @call_div() -> !rec_div_t {
    %n = cir.const #cir.int<10> : !s32i
    %d = cir.const #cir.int<3> : !s32i
    %result = cir.call @mock_div(%n, %d) : (!s32i, !s32i) -> !rec_div_t
    cir.return %result : !rec_div_t
  }
  // CHECK: cir.func @call_div() -> !u64i
  // CHECK:   %[[RAW:.*]] = cir.call @mock_div
  // CHECK:   cir.alloca !u64i, !cir.ptr<!u64i>, ["coerce"]
  // CHECK:   cir.store %[[RAW]]
  // CHECK:   cir.cast bitcast {{.*}} : !cir.ptr<!u64i> -> !cir.ptr<!rec_div_t>
  // CHECK:   cir.load {{.*}} : !cir.ptr<!rec_div_t>, !rec_div_t

  // --- Declaration rewriting ---

  cir.func private @extern_div(!s32i, !s32i) -> !rec_div_t
  // CHECK: cir.func private @extern_div(!s32i, !s32i) -> !u64i

  cir.func @call_extern(%a : !s32i, %b : !s32i) -> !rec_div_t {
    %r = cir.call @extern_div(%a, %b) : (!s32i, !s32i) -> !rec_div_t
    cir.return %r : !rec_div_t
  }
  // CHECK: cir.func @call_extern(%arg0: !s32i, %arg1: !s32i) -> !u64i
  // CHECK:   %[[R:.*]] = cir.call @extern_div(%arg0, %arg1) : (!s32i, !s32i) -> !u64i

  // --- Struct argument coercion (memory-based) ---

  cir.func @takes_pair(%p : !rec_div_t) -> !rec_div_t {
    cir.return %p : !rec_div_t
  }
  // CHECK: cir.func @takes_pair(%arg0: !u64i) -> !u64i
  // CHECK:   %[[A:.*]] = cir.alloca !u64i, !cir.ptr<!u64i>, ["coerce"]
  // CHECK:   cir.store %arg0, %[[A]]
  // CHECK:   %[[P:.*]] = cir.cast bitcast %[[A]] : !cir.ptr<!u64i> -> !cir.ptr<!rec_div_t>
  // CHECK:   %[[V:.*]] = cir.load %[[P]] : !cir.ptr<!rec_div_t>, !rec_div_t

  // Call site with struct argument coercion.
  cir.func @call_takes_pair() -> !rec_div_t {
    %tmp = cir.alloca !rec_div_t, !cir.ptr<!rec_div_t>, ["tmp"] {alignment = 4 : i64}
    %val = cir.load %tmp : !cir.ptr<!rec_div_t>, !rec_div_t
    %r = cir.call @takes_pair(%val) : (!rec_div_t) -> !rec_div_t
    cir.return %r : !rec_div_t
  }
  // CHECK: cir.func @call_takes_pair() -> !u64i
  // CHECK:   %[[V:.*]] = cir.load {{.*}} : !cir.ptr<!rec_div_t>, !rec_div_t
  // CHECK:   %[[CA:.*]] = cir.alloca !rec_div_t, !cir.ptr<!rec_div_t>, ["coerce"]
  // CHECK:   cir.store %[[V]], %[[CA]]
  // CHECK:   %[[CP:.*]] = cir.cast bitcast %[[CA]] : !cir.ptr<!rec_div_t> -> !cir.ptr<!u64i>
  // CHECK:   %[[CV:.*]] = cir.load %[[CP]] : !cir.ptr<!u64i>, !u64i
  // CHECK:   cir.call @takes_pair(%[[CV]]) : (!u64i) -> !u64i
}
